### PR TITLE
Array and relations

### PR DESCRIPTION
**Pull request by mariobrosch**
Added the array type as optional, so you can add the option --arraytype for startup. See my mentioned issue for details about arrays. 

For relations to other objects I have added the hasMany and belongsTo options to the attribute. The each block has become a bit larger, but I didnt get it smaller without losing readability.

PS: Pasted the whole file into the git-editor. Problem occured is that my spacing is different and git sees almost the whole file as change. Sorry. The things which have been changed are the options and the _.each block

### CODE REVIEW

**Comment by mariobrosch** [comment]
PS: When you accept this merge, when is it available in the installer through ember command line?

**Comment by queenvictoria** [comment]
Hi Mario thanks for the PR. I'll rewrite it because I like good commits without whitespace errors.

What editor did you use? I am using 2 space tabs with some clean up tools to prevent bad whitespace. This is all easy in Sublime Text.

**Comment by mariobrosch** [comment]
i used 4 at the time, last few weeks im using 2 :).

visual studio code

**Comment by queenvictoria** [comment]
I've rewritten this without the whitespace and a little clearer. Its in the [object-array](/queenvictoria/ember-cli-openapi-generate/tree/object-array) branch.

**Pull request closed without merging**
